##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    use_usd_kinematics: False
    urdf_path: "robot/G1_120s/G1.urdf"
    asset_root_path: "robot/G1_120s"
    isaac_usd_path: ""
    usd_robot_root: null
    usd_path: null

    base_link: "base_link"
    ee_link: "right_gripper_center"
    link_names: ["right_gripper_center", "gripper_center"]

    collision_link_names:
      [
        "base_link",
        "link-up-down_body",
        "link-pitch_body",
        "link-pitch_head",
        "base_link_r",
        "Link1_r",
        "Link2_r",
        "Link3_r",
        "Link4_r",
        "Link5_r",
        "Link6_r",
        "Link7_r",
        "right_base_link",
        "right_Left_01_Link",
        "right_Left_00_Link",
        "right_Left_Support_Link",
        "right_Left_Pad_Link",
        "right_Right_01_Link",
        "right_Right_00_Link",
        "right_Right_Support_Link",
        "right_Right_Pad_Link",
        "attached_object",
        "base_link_l",
        "Link1_l",
        "Link2_l",
        "Link3_l",
        "Link4_l",
        "Link5_l",
        "Link6_l",
        "Link7_l",
        "left_base_link",
        "left_Left_01_Link",
        "left_Left_00_Link",
        "left_Left_Support_Link",
        "left_Left_Pad_Link",
        "left_Right_01_Link",
        "left_Right_00_Link",
        "left_Right_Support_Link",
        "left_Right_Pad_Link",
        "left_attached_object",
      ]
    collision_spheres:
      base_link:
        - "center": [-0.109, 0.0, 0.425]
          "radius": 0.15
        - "center": [-0.118, 0.0, 1.116]
          "radius": 0.15
        - "center": [-0.111, 0.0, 0.598]
          "radius": 0.15
        - "center": [-0.113, 0.0, 0.77]
          "radius": 0.15
        - "center": [-0.116, 0.0, 0.943]
          "radius": 0.15
      link-up-down_body:
        - "center": [0.13, -0.0, -0.0]
          "radius": 0.05
      link-pitch_body:
        - "center": [0.113, -0.0, -0.0]
          "radius": 0.08
        - "center": [0.211, -0.0, -0.0]
          "radius": 0.08
      link-pitch_head:
        - "center": [-0.017, 0.031, 0.0]
          "radius": 0.05
      base_link_r:
        - "center": [0.0, 0.0, 0.027]
          "radius": 0.04
      Link1_r:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.04
        - "center": [0.0, 0.0, 0.073]
          "radius": 0.04
        - "center": [0.0, 0.0, 0.033]
          "radius": 0.04
      Link2_r:
        - "center": [0.0, -0.086, 0]
          "radius": 0.04
      Link3_r:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.03
        - "center": [-0.0, 0.0, -0.141]
          "radius": 0.03
        - "center": [-0.0, 0.0, -0.04]
          "radius": 0.03
        - "center": [-0.0, 0.0, -0.084]
          "radius": 0.03
      Link4_r:
        - "center": [-0.0, 0.071, 0]
          "radius": 0.03
      Link5_r:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.03
        - "center": [0.0, -0.0, -0.093]
          "radius": 0.03
      Link6_r:
        - "center": [-0.0, -0.065, 0]
          "radius": 0.03
      Link7_r:
        - "center": [0.0, -0.0, -0.017]
          "radius": 0.03
      right_base_link:
        - "center": [0.0, 0.0, 0.03]
          "radius": 0.03
        - "center": [0.0, 0.0, 0.082]
          "radius": 0.02
        - "center": [0.0, 0.0, 0.111]
          "radius": 0.02
      right_Left_01_Link:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.005
        - "center": [0.007, 0.005, 0.0]
          "radius": 0.005
        - "center": [0.013, 0.009, 0.0]
          "radius": 0.005
        - "center": [0.019, 0.013, 0.0]
          "radius": 0.005
      right_Left_00_Link:
        - "center": [-0.0075, 0.009, -0.0075]
          "radius": 0.006
        - "center": [-0.01, 0.015, -0.0075]
          "radius": 0.006
        - "center": [-0.013, 0.02, -0.0075]
          "radius": 0.006
        - "center": [-0.018, 0.026, -0.0075]
          "radius": 0.006
        - "center": [-0.023, 0.034, -0.0075]
          "radius": 0.006
        - "center": [-0.028, 0.042, -0.0075]
          "radius": 0.006
        - "center": [-0.0075, 0.009, -0.0075]
          "radius": 0.006
      right_Left_Support_Link:
        - "center": [-0.0, 0.001, 0.008]
          "radius": 0.005
        - "center": [0.001, 0.0, -0.009]
          "radius": 0.005
        - "center": [-0.005, 0.01, 0.007]
          "radius": 0.005
        - "center": [-0.004, 0.01, -0.008]
          "radius": 0.005
        - "center": [-0.008, 0.017, 0.007]
          "radius": 0.005
        - "center": [-0.008, 0.017, -0.008]
          "radius": 0.005
        - "center": [-0.009, 0.032, 0.008]
          "radius": 0.005
        - "center": [-0.01, 0.024, 0.008]
          "radius": 0.005
        - "center": [-0.008, 0.032, -0.008]
          "radius": 0.005
        - "center": [-0.01, 0.025, -0.009]
          "radius": 0.005
        - "center": [-0.013, 0.029, 0.0]
          "radius": 0.008
      right_Left_Pad_Link:
        - "center": [0.0, -0.016, 0.0075]
          "radius": 0.005
        - "center": [0.0, 0.021, 0.0075]
          "radius": 0.005
        - "center": [0.0, 0.021, -0.0075]
          "radius": 0.005
        - "center": [0.0, -0.012, 0.0075]
          "radius": 0.005
        - "center": [0.0, -0.008, 0.0075]
          "radius": 0.005
        - "center": [0.0, -0.004, 0.0075]
          "radius": 0.005
      right_Right_01_Link:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.005
        - "center": [0.007, 0.004, -0.0]
          "radius": 0.005
        - "center": [0.014, 0.009, -0.0]
          "radius": 0.005
        - "center": [0.02, 0.013, -0.0]
          "radius": 0.005
      right_Right_00_Link:
        - "center": [-0.0075, 0.009, -0.0075]
          "radius": 0.006
        - "center": [-0.01, 0.015, -0.0075]
          "radius": 0.006
        - "center": [-0.013, 0.02, -0.0075]
          "radius": 0.006
        - "center": [-0.018, 0.026, -0.0075]
          "radius": 0.006
        - "center": [-0.023, 0.034, -0.0075]
          "radius": 0.006
        - "center": [-0.028, 0.042, -0.0075]
          "radius": 0.006
        - "center": [-0.0075, 0.009, -0.0075]
          "radius": 0.006
      right_Right_Support_Link:
        - "center": [-0.0, 0.001, 0.008]
          "radius": 0.005
        - "center": [0.001, 0.0, -0.009]
          "radius": 0.005
        - "center": [-0.005, 0.01, 0.007]
          "radius": 0.005
        - "center": [-0.004, 0.01, -0.008]
          "radius": 0.005
        - "center": [-0.008, 0.017, 0.007]
          "radius": 0.005
        - "center": [-0.008, 0.017, -0.008]
          "radius": 0.005
        - "center": [-0.009, 0.032, 0.008]
          "radius": 0.005
        - "center": [-0.01, 0.024, 0.008]
          "radius": 0.005
        - "center": [-0.008, 0.032, -0.008]
          "radius": 0.005
        - "center": [-0.01, 0.025, -0.009]
          "radius": 0.005
      right_Right_Pad_Link:
        - "center": [0.0, 0.021, 0.0075]
          "radius": 0.005
        - "center": [0.0, 0.021, -0.0075]
          "radius": 0.005
        - "center": [-0.0, -0.015, 0.0075]
          "radius": 0.005
        - "center": [0.0, 0.017, 0.0075]
          "radius": 0.005
        - "center": [0.0, 0.013, 0.0075]
          "radius": 0.005
        - "center": [0.0, 0.009, 0.0075]
          "radius": 0.005
        - "center": [0.0, 0.005, 0.0075]
          "radius": 0.005
      base_link_l:
        - "center": [0.0, 0.0, 0.027]
          "radius": 0.04
      Link1_l:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.04
        - "center": [0.0, 0.0, 0.073]
          "radius": 0.04
        - "center": [0.0, 0.0, 0.033]
          "radius": 0.04
      Link2_l:
        - "center": [0.0, 0.086, 0]
          "radius": 0.04
      Link3_l:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.03
        - "center": [-0.0, 0.0, 0.141]
          "radius": 0.03
        - "center": [-0.0, 0.0, 0.04]
          "radius": 0.03
        - "center": [-0.0, 0.0, 0.084]
          "radius": 0.03
      Link4_l:
        - "center": [-0.0, 0.071, 0]
          "radius": 0.03
      Link5_l:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.03
        - "center": [0.0, -0.0, -0.093]
          "radius": 0.03
      Link6_l:
        - "center": [-0.0, -0.065, 0]
          "radius": 0.03
      Link7_l:
        - "center": [0.0, -0.0, -0.017]
          "radius": 0.03
      left_base_link:
        - "center": [0.0, 0.0, 0.03]
          "radius": 0.03
      left_Left_01_Link:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.005
      left_Left_00_Link:
        - "center": [-0.0075, 0.009, -0.0075]
          "radius": 0.006
      left_Left_Support_Link:
        - "center": [-0.0, 0.001, 0.008]
          "radius": 0.005
        - "center": [0.001, 0.0, -0.009]
          "radius": 0.005
        - "center": [-0.005, 0.01, 0.007]
          "radius": 0.005
        - "center": [-0.004, 0.01, -0.008]
          "radius": 0.005
        - "center": [-0.008, 0.017, 0.007]
          "radius": 0.005
        - "center": [-0.008, 0.017, -0.008]
          "radius": 0.005
      left_Left_Pad_Link:
        - "center": [0.0, -0.016, 0.0075]
          "radius": 0.005
        - "center": [0.0, 0.021, 0.0075]
          "radius": 0.005
        - "center": [0.0, -0.012, 0.0075]
          "radius": 0.005
        - "center": [0.0, -0.008, 0.0075]
          "radius": 0.005
        - "center": [0.0, -0.004, 0.0075]
          "radius": 0.005
        - "center": [0.0, 0.001, 0.0075]
          "radius": 0.005
      left_Right_01_Link:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.005
      left_Right_00_Link:
        - "center": [-0.0075, 0.009, -0.0075]
          "radius": 0.006
      left_Right_Support_Link:
        - "center": [-0.0, 0.001, 0.008]
          "radius": 0.005
        - "center": [0.001, 0.0, -0.009]
          "radius": 0.005
        - "center": [-0.005, 0.01, 0.007]
          "radius": 0.005
        - "center": [-0.004, 0.01, -0.008]
          "radius": 0.005
        - "center": [-0.008, 0.017, 0.007]
          "radius": 0.005
        - "center": [-0.008, 0.017, -0.008]
          "radius": 0.005
      left_Right_Pad_Link:
        - "center": [0.0, 0.021, 0.0075]
          "radius": 0.005
        - "center": [-0.0, -0.015, 0.0075]
          "radius": 0.005
        - "center": [0.0, 0.017, 0.0075]
          "radius": 0.005
        - "center": [0.0, 0.013, 0.0075]
          "radius": 0.005
        - "center": [0.0, 0.009, 0.0075]
          "radius": 0.005
        - "center": [0.0, 0.005, 0.0075]
          "radius": 0.005

    collision_sphere_buffer: 0.0
    extra_collision_spheres:
      { "attached_object": 50, "left_attached_object": 50 }
    self_collision_ignore:
      {
        "base_link": ["link-up-down_body", "link-pitch_body"],
        "link-up-down_body": ["base_link", "link-pitch_body"],
        "link-pitch_body": ["link-up-down_body", "base_link_r", "base_link_l"],
        "link-pitch_head":
          [
            "base_link_r",
            "Link1_r",
            "Link2_r",
            "link3_r",
            "base_link_l",
            "Link1_l",
          ],
        "base_link_r": ["Link1_r", "link-pitch_body"],
        "Link1_r": ["base_link_r", "Link2_r", "Link3_r"],
        "Link2_r": ["Link1_r", "Link3_r"],
        "Link3_r":
          ["Link2_r", "Link4_r", "left_attached_object", "attached_object"],
        "Link4_r":
          ["Link3_r", "Link5_r", "left_attached_object", "attached_object"],
        "Link5_r":
          ["Link4_r", "Link6_r", "left_attached_object", "attached_object"],
        "Link6_r":
          ["Link5_r", "Link7_r", "left_attached_object", "attached_object"],
        "Link7_r":
          [
            "Link6_r",
            "right_base_link",
            "left_attached_object",
            "attached_object",
          ],
        "right_base_link":
          [
            "Link7_r",
            "right_Left_01_Link",
            "right_Right_01_Link",
            "left_attached_object",
            "attached_object",
          ],
        "right_Left_01_Link":
          ["right_Left_00_Link", "left_attached_object", "attached_object"],
        "right_Left_00_Link":
          [
            "right_Left_Support_Link",
            "left_attached_object",
            "attached_object",
          ],
        "right_Left_Support_Link":
          ["right_Left_Pad_Link", "left_attached_object", "attached_object"],
        "right_Left_Pad_Link":
          ["right_Right_Pad_Link", "left_attached_object", "attached_object"],
        "right_Right_01_Link":
          ["right_Right_00_Link", "left_attached_object", "attached_object"],
        "right_Right_00_Link":
          [
            "right_Right_Support_Link",
            "left_attached_object",
            "attached_object",
          ],
        "right_Right_Support_Link":
          ["right_Right_Pad_Link", "left_attached_object", "attached_object"],
        "right_Right_Pad_Link":
          ["right_Left_Pad_Link", "left_attached_object", "attached_object"],
        "base_link_l": ["Link1_l", "link-pitch_body"],
        "Link1_l": ["base_link_l", "Link2_l", "Link3_l"],
        "Link2_l": ["Link1_l", "Link3_l"],
        "Link3_l":
          ["Link2_l", "Link4_l", "left_attached_object", "attached_object"],
        "Link4_l":
          ["Link3_l", "Link5_l", "left_attached_object", "attached_object"],
        "Link5_l":
          ["Link4_l", "Link6_l", "left_attached_object", "attached_object"],
        "Link6_l":
          ["Link5_l", "Link7_l", "left_attached_object", "attached_object"],
        "Link7_l":
          [
            "Link6_l",
            "left_base_link",
            "left_attached_object",
            "attached_object",
          ],
        "left_base_link":
          [
            "Link7_l",
            "left_Left_01_Link",
            "left_Right_01_Link",
            "left_attached_object",
            "attached_object",
          ],
        "left_Left_01_Link":
          ["left_Left_00_Link", "left_attached_object", "attached_object"],
        "left_Left_00_Link":
          ["left_Left_Support_Link", "left_attached_object", "attached_object"],
        "left_Left_Support_Link":
          ["left_Left_Pad_Link", "left_attached_object", "attached_object"],
        "left_Left_Pad_Link":
          ["left_Right_Pad_Link", "left_attached_object", "attached_object"],
        "left_Right_01_Link":
          ["left_Right_00_Link", "left_attached_object", "attached_object"],
        "left_Right_00_Link":
          [
            "left_Right_Support_Link",
            "left_attached_object",
            "attached_object",
          ],
        "left_Right_Support_Link":
          ["left_Right_Pad_Link", "left_attached_object", "attached_object"],
        "left_Right_Pad_Link":
          ["left_Left_Pad_Link", "left_attached_object", "attached_object"],
      }
    self_collision_buffer: { "right_finger_base": 0 }
    use_global_cumul: True
    extra_links:
      {
        "attached_object":
          {
            "parent_link_name": "right_base_link",
            "link_name": "attached_object",
            "fixed_transform": [0, 0, 0.18, 1, 0, 0, 0],
            "joint_type": "FIXED",
            "joint_name": "attach_joint",
          },
        "left_attached_object":
          {
            "parent_link_name": "left_base_link",
            "link_name": "left_attached_object",
            "fixed_transform": [0, 0, 0.18, 1, 0, 0, 0],
            "joint_type": "FIXED",
            "joint_name": "left_attach_joint",
          },
      }
    lock_joints:
      {
        "joint_lift_body": 0.2,
        "joint_body_pitch": 0.5,
        "right_Left_1_Joint": 1,
        "right_Left_0_Joint": 0,
        "right_Left_Support_Joint": 1,
        "right_Right_1_Joint": -1,
        "right_Right_0_Joint": 0,
        "right_Right_Support_Joint": 1,
        "left_Left_1_Joint": 1,
        "left_Left_0_Joint": 0,
        "left_Left_Support_Joint": 1,
        "left_Right_1_Joint": -1,
        "left_Right_0_Joint": 0,
        "left_Right_Support_Joint": 1,
      }

    mesh_link_names:
      [
        "base_link",
        "link-up-down_body",
        "link-pitch_body",
        "base_link_r",
        "Link1_r",
        "Link2_r",
        "Link3_r",
        "Link4_r",
        "Link5_r",
        "Link6_r",
        "Link7_r",
        "right_base_link",
        "right_Left_01_Link",
        "right_Left_00_Link",
        "right_Left_Support_Link",
        "right_Left_Pad_Link",
        "right_Right_01_revoluteLink",
        "right_Right_00_Link",
        "right_Right_Support_Link",
        "right_Right_Pad_Link",
        "base_link_l",
        "Link1_l",
        "Link2_l",
        "Link3_l",
        "Link4_l",
        "Link5_l",
        "Link6_l",
        "Link7_l",
        "left_base_link",
        "left_Left_01_Link",
        "left_Left_00_Link",
        "left_Left_Support_Link",
        "left_Left_Pad_Link",
        "right_Right_01_revoluteLink",
        "left_Right_00_Link",
        "left_Right_Support_Link",
        "left_Right_Pad_Link",
      ]
    cspace:
      joint_names:
        [
          "joint_lift_body",
          "joint_body_pitch",
          "Joint1_r",
          "Joint2_r",
          "Joint3_r",
          "Joint4_r",
          "Joint5_r",
          "Joint6_r",
          "Joint7_r",
          "right_Left_1_Joint",
          "right_Left_0_Joint",
          "right_Left_Support_Joint",
          "right_Right_1_Joint",
          "right_Right_0_Joint",
          "right_Right_Support_Joint",
          "Joint1_l",
          "Joint2_l",
          "Joint3_l",
          "Joint4_l",
          "Joint5_l",
          "Joint6_l",
          "Joint7_l",
          "left_Left_1_Joint",
          "left_Left_0_Joint",
          "left_Left_Support_Joint",
          "left_Right_1_Joint",
          "left_Right_0_Joint",
          "left_Right_Support_Joint",
        ]

      retract_config:
        [
          0,
          0.5,
          2.07,
          -0.61,
          -1.57,
          1,
          -1.57,
          -1.57,
          1.57,
          1.0,
          0.0,
          1.0,
          -1.0,
          0.0,
          1.0,
          -2.07,
          0.61,
          1.57,
          -1,
          1.57,
          1.57,
          -1.57,
          1.0,
          0.0,
          1.0,
          -1.0,
          0.0,
          1.0,
        ]
      null_space_weight:
        [
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
        ]
      cspace_distance_weight:
        [
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
          1.0,
        ]
      max_jerk: 500.0
      max_acceleration: 15.0
