optimizer:
  initial_step: 1e-2
  xtol_rel: 1.0e-5 # relative x tolerance
  ftol_rel: 1.0e-5 # relative f tolerance
  maxeval: 200 # max times solver can try
  maxtime: 0.005 # [s] max solver time limit

standard_ik:
  pos_weight: 40.0
  ori_weight: 8.0
  pos_elbow_weight: 10.0
  ori_elbow_weight: 8.0
  upper_arm_coef: 2.0 # upper arm means first 3 joints
  elbow_coef: 1.0

relaxed_ik:
  pos_weight: 40.0
  ori_weight: 8.0
  min_velocity_weight: 1.0
  min_acceleration_weight: 0.0
  min_jerk_weight: 0.0
  joint_limits_weight: 1.0
  pos_elbow_weight: 0.0
  ori_elbow_weight: 0.0
  upper_arm_coef: 2.0 # upper arm means first 3 joints
  elbow_coef: 1.0
